### ISSUE TITLE
Test for endGame() removes the "keydown" event listener target doesn't match start method

### ISSUE THREAD

**Issue by nombytecode** [learn-co-students/javascript-rock-dodger-bootcamp-prep-000#192]
lines 152-159 on the index-test.js file wants you to unset the event on document

but the start method adds the event listener on the window object 

test file:
[https://github.com/learn-co-students/javascript-rock-dodger-bootcamp-prep-000/blob/master/test/index-test.js#L152-L159](url)

[https://github.com/learn-co-students/javascript-rock-dodger-bootcamp-prep-000/blob/master/index.js#L149](url)

is this intentional?

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/javascript-rock-dodger/pull/17

Thanks @nombytecode !
