### ISSUE TITLE
instructions on lines 44 and 45 are incorrect in order to match the tests

### ISSUE THREAD

**Issue by aguyinmontreal** [learn-co-students/javascript-rock-dodger-bootcamp-prep-000#335]
instructions on lines 44 and 45 are incorrect in order to match the tests

**Comment by bhollan** [comment]
Issues should be filed on the `learn-co-curriculum` copy of this lab.
See the [list of current issues](https://github.com/learn-co-curriculum/javascript-rock-dodger/issues).

If you'd like to re-submit your PR for this, you can do it according to the [CONTRIBUTING.md](https://github.com/learn-co-curriculum/javascript-rock-dodger/issues) file from the above repo.

CC @gj @aturkewi
